# This file was generated by stubgen-pyx v0.1.1
"""
This is a module for testing stub file generation.
"""

from test_project.test2 import ImportedClass
from typing import List

class PythonClass:
    """
    Injects type annotations when possible.
    """

    x: int
    y: int
    z: int

    def __init__(self, x: "int", y: "int", z: "int") -> None: ...

class TestClass:
    """
    This is a class for testing stub file generation.
    """

    _test_class_2: TestClass2

    def __init__(self):
        """
        A docstring for __init__
        """
    def b(self):
        """
        A docstring for b
        """
    def c(self):
        """
        A docstring for c
        """
    def test_class_2(self) -> TestClass2: ...

class TestClass2:
    def __init__(self):
        """
        A docstring for __init__
        """

def func() -> ImportedClass: ...
def imported_class_test() -> ImportedClass: ...
def print_dict(d: dict) -> List[bool]:
    """
    Follows imports.
    """

def public_function(x: int) -> bool:
    """
    Shows cpdef functions in the stub.
    """
