# This file was generated by stubgen-pyx v0.1.1
"""
This is a test of importing modules.
"""

from typing import Dict, Tuple as tup

X: ImportedClass

class ImportedClass:
    """
    A docstring for ImportedClass
    """

    _private_field: int
    public_field: int

    def __init__(self):
        """
        A docstring for __init__
        """
    def public_method(self) -> int: ...

class RegularClass:
    x: int
    y: float
    z: complex

    def __init__(self, /, *args, **kwargs):
        """Initialize self.  See help(type(self)) for accurate signature."""

def returns_dict() -> Dict[int, int]: ...
def returns_tuple() -> tup[int, int]: ...
