# This file was generated by stubgen-pyx v0.1.0
"""
This is a test of importing modules.
"""

class ImportedClass:
    """
    A docstring for ImportedClass
    """

    def __init__(self):
        """
        A docstring for __init__
        """